server:
  port: 8888
spring:
  application:
    name: ms-config-server
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: "file:C:/Users/user/Documents/DesarrolloProgramacion/carpeta"
#          uri: https://github.com/repositorio.git
#          username: 
#          password: 
