server:
  port: 8888
spring:
  application:
    name: ms-config-server
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/ealfriadez/carpeta.git
          username: ealfriadez
          password: Casa654321#
#          uri: "file:E:/Users/Michael/Documents/Desarrollo_IntelliJ IDEA/codearti/carpeta"
#          uri: "file:C:/Users/user/Documents/DesarrolloProgramacion/carpeta"
#          uri: git@github.com:ealfriadez/carpeta.git