server:
  port: 8888
spring:
  application:
    name: ms-config-server
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: "file:E:/Users/Michael/Documents/Desarrollo_IntelliJ IDEA/codearti/carpeta"
#          uri: "file:C:/Users/user/Documents/DesarrolloProgramacion/carpeta"
#         uri: https://github.com/repositorio.git
#          uri: git@github.com:ealfriadez/carpeta.git
#          username: 
#          password: 
